### ISSUE TITLE
Preferences Bugs

### ISSUE THREAD

**Issue by RobertBColton** [JoshDreamland/JoshEdit#52]
Ok, since you were unaware, I figured I should take the time to point out the issues to you.
- [ ] Keyboard preferences are all disabled, can't change any of them.
- [ ] Some of the built in syntax schemes are disabled.
- [ ] Switching the combo box to some schemes stops the UI from repainting.

![ComboBox Repainting Glitch](https://cloud.githubusercontent.com/assets/3212801/12855441/7ff6fc62-cc0d-11e5-95b8-3541afc8598a.png)

For these reasons I have decided to hide the JoshEdit preferences in the next LGM release until they are finished. I did not even bother to test a posteriori if the serialization works because of the UI bugs.

**Comment by JoshDreamland** [comment]
I take this bug report to mean "The UI is confusing." There's nothing to be done about this. I believe the repainting problem is a Windows theme issue. See if it still persists. It's not present in the Swing or Metal themes, or if it is, I can't reproduce it.

You are not allowed to edit built-in themes. You must copy them first by pressing "New." It will prompt you for a name.

You don't just type c-t-r-l-space-plus-space-C into the key selector. You press the combo you want to set.
